# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41d6207183eb20b016419ec3d877d1aee20ee406bee8e78f26ef8a88da842fc773e6661e4d945a9ec483110ff3dc888e3b5e3b703d153f9dc2c593d07304a1d8

test:
  secret_key_base: de4d15223110d6a8ae1cc8b9fa28256f48438c68dda786c799ed13c8b2778fbe7b12411ddd7711d05b8572557d3039309be0a024ba44a8204511a29485c76d9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
